Update bin/compile
back to 5.3

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,73 +1,66 @@
-mkdir -p /app
- 
- 
-# Prepare the filesystem
-mkdir -p /tmp/build
-cd /tmp/build
- 
- 
-# Compiling Apache
-curl http://www.us.apache.org/dist/httpd/httpd-2.2.22.tar.gz | tar xzf -
- 
-cd httpd-2.2.22
-./configure --prefix=/app/apache --with-z=/usr/local/zlib --enable-rewrite --enable-so --enable-deflate --enable-expires --enable-headers
-make && make install
-cd ..
- 
- 
-# Apache libraries
-mkdir -p /app/php/ext
-cp /app/apache/lib/libapr-1.so /app/php/ext
-cp /app/apache/lib/libaprutil-1.so /app/php/ext
-cp /app/apache/lib/libapr-1.so.0 /app/php/ext
-cp /app/apache/lib/libaprutil-1.so.0 /app/php/ext
- 
- 
-# Compiling PHP
-curl -L http://php.net/get/php-5.4.9.tar.gz/from/us1.php.net/mirror | tar xzf -
- 
-cd php-5.4.9
-./configure --prefix=/app/php --with-apxs2=/app/apache/bin/apxs --with-pgsql --with-pdo-pgsql --with-iconv --with-config-file-path=/app/php --with-openssl --with-readline --enable-mbstring --with-gd --with-jpeg-dir=/usr --with-curl=/usr
-make && make install
-cd ..
- 
- 
-# PHP Extensions
-cp php-5.4.9/libs/libphp5.so /app/apache/modules/
- 
- 
-# APC
-curl http://pecl.php.net/get/APC/3.1.13 | tar xzf -
- 
-cd APC-3.1.13
-/app/php/bin/phpize
-./configure --enable-apc --enable-apc-mmap --with-php-config=/app/php/bin/php-config
-make && make install
-cd ..
- 
-# MongoDB
-curl http://pecl.php.net/get/mongo/1.3.2 | tar xzf -
- 
-cd mongo-1.3.2
-/app/php/bin/phpize
-./configure --with-php-config=/app/php/bin/php-config
-make && make install
-cd ..
- 
-mv /app/php/lib/php/extensions/no-debug-non-zts-20100525/*.so /app/php/ext/
-rm -rf /app/php/lib/php/extensions
- 
- 
-# Create packages
-cd /app
- 
-echo '2.2.22' > apache/VERSION
-tar -zcvf apache.tar.gz apache
- 
-echo '5.4.9' > php/VERSION
-tar -zcvf php.tar.gz php
- 
- 
-# Upload to your server using SCP
-# scp '-P 22' apache.tar.gz root@domain.tld:/path/to
-# scp '-P 22' php.tar.gz root@domain.tld:/path/to
+#!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir>
+
+# fail fast
+set -e
+
+# config
+APACHE_VERSION="2.2.22"
+APACHE_PATH="apache"
+PHP_VERSION="5.3.10"
+PHP_PATH="php"
+
+BIN_DIR=$(dirname $0)
+BUILD_DIR=$1
+CACHE_DIR=$2
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
+
+# include .files when moving things around
+shopt -s dotglob
+
+cd $BUILD_DIR
+
+# move app things to www
+mkdir -p $CACHE_DIR/www
+mv * $CACHE_DIR/www
+mv $CACHE_DIR/www .
+
+# keep Procfile
+if [ -f www/Procfile ]; then
+  mv www/Procfile .
+fi
+
+APACHE_URL="https://s3.amazonaws.com/php-lp/apache-$APACHE_VERSION.tar.gz"
+echo "-----> Bundling Apache version $APACHE_VERSION"
+curl --silent --max-time 60 --location "$APACHE_URL" | tar xz
+
+PHP_URL="https://s3.amazonaws.com/php-lp/php-$PHP_VERSION.tar.gz"
+echo "-----> Bundling PHP version $PHP_VERSION"
+curl --silent --max-time 60 --location "$PHP_URL" | tar xz
+
+# update config files
+cp $LP_DIR/conf/httpd.conf $APACHE_PATH/conf
+cp $LP_DIR/conf/php.ini php
+
+# make php available on bin
+mkdir -p bin
+ln -s /app/php/bin/php bin/php
+
+cat >>boot.sh <<EOF
+for var in \`env|cut -f1 -d=\`; do
+  echo "PassEnv \$var" >> /app/apache/conf/httpd.conf;
+done
+touch /app/apache/logs/error_log
+touch /app/apache/logs/access_log
+tail -F /app/apache/logs/error_log &
+tail -F /app/apache/logs/access_log &
+export LD_LIBRARY_PATH=/app/php/ext
+export PHP_INI_SCAN_DIR=/app/www
+echo "Launching apache"
+exec /app/apache/bin/httpd -DNO_DETACH
+EOF
+
+chmod +x boot.sh
+
+# clean the cache
+rm -rf $CACHE_DIR/*
